# Site settings
title: Jonah.
email: jonah.moeller@gmail.com
description: My name is Jonah MÃ¶ller and I'm a passionate Web Developer from Hamburg; I enjoy delivering bespoke applications and websites to fit a client's needs.
github_username:  snapsnapturtle

# Build settings
markdown: kramdown
